# Clans config

# Database configuration
database:

  # Database type. Supported values: h2, sqlite
  type: h2

  # Database name
  dbname: clans.h2

  # Database user. Leave empty for h2/sqlite
  user: ''

  # Database password. Leave empty for h2/sqlite
  password: ''

  # Database address
  address: './'

# Clan configuration
clan:
  # Delay between saving clans to database. In seconds
  flush-delay: 300
  # Allow transferring clan to a new leader by setting his rank to LEADER
  allow-transfer: true