name: Clans-Bukkit
description: ClanSystem
version: '${project.version}'
main: ru.whbex.develop.clans.bukkit.MainBukkit
api-version: '1.20'
commands:
  clans:
    description: 'Temp clans command'
  clan:
    description: 'Clan management command'
  clansplugin:
    description: 'Plugin management command'
